### ISSUE TITLE
Add l10n label

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/l10n-script#11]
The label exists, so why not make use of it?

**Comment by WorldLanguages** [comment]
Add it to what?

**Comment by Samq64** [comment]
The translation pull requests on the main repository.

**Comment by Hans5958** [comment]
Let's see if this works tommorow... (didn't want to test it today, already made enough noise today)

**Comment by Samq64** [comment]
No labels were automatically added on https://github.com/ScratchAddons/ScratchAddons/pull/7122.

**Comment by Hans5958** [comment]
And it failed! At least the PR is created, so nothing value was lost.

Fixed it, let's see how it goes ~~tommorow~~ today.

**Comment by DNin01** [comment]
Was just about to report the error here 😄

Nice catch!

**Comment by DNin01** [comment]
🎉

**Comment by Hans5958** [comment]
Alright, ScratchAddons/ScratchAddons#7123 had it. Hope you liked it.
